# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
stages:
  - stage: TerraformValidate
    jobs:
      - job: TerrafomrValidateJob
        continueOnError: false
        steps:
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/terraform-manifests'
              ArtifactName: 'terraform-manifests-out'
              publishLocation: 'Container'

          