apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-07-10T00:03:36Z"
  generation: 1
  labels:
    app: simple-go-app
  name: simple-go-app
  namespace: app
  resourceVersion: "14130"
  uid: 00a33547-a0f2-4334-84ca-479f20ce753c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: simple-go-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simple-go-app
    spec:
      imagePullSecrets:
      - name: ghcr-creds
      containers:
      - image: ghcr.io/vijai-veerapandian/simple-go-app:1.0.0
        imagePullPolicy: IfNotPresent
        name: simple-go-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
