apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-go-app
  name: simple-go-app-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-go-app
  type: "80"
status:
  loadBalancer: {}
