apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-go-app
  name: simple-go-app
  namespace: app
spec:
  ports:
  - port: 8989
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-go-app
  type: ClusterIP
